name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose -l 120"
          src: "./src"
          version: "22.10.0"
      -uses: jpetrucciani/mypy-check@master
        with:
          path: '.'
      - name: Run unit tests
          run: python -m pytest --import-mode=append tests/